### ISSUE TITLE
[TES] Docker integration with GitHub Packages

### ISSUE THREAD

**Issue by aendeavor** [aendeavor/i3buntu#22]
# Docker-Integration with GitHub's packages-feature

## Description

The new _GitHub Packages_ shall be used to create Docker-Images and for testing.

## Tasks

* [x] Create a Docker-Hub account
* [x] Create a i3buntu Docker-Hub repository
* [x] Create the directives to auto-build
* [x] Write a correct `Dockerfile`
* [x] Write a separate `docker.sh` packaging and configuration script
* [x] Integrate the docker-images into GitHub-Packages

## Meta

Rainer is your friend.

## Related

**Comment by aendeavor** [comment]
Done. [01.01.20-18:22]
