### ISSUE TITLE
[DOC] Better logging

### ISSUE THREAD

**Issue by aendeavor** [aendeavor/i3buntu#31]
# Better logging

## Description

The current logging lacks the ability to show ERRORs, WARNINGs and SUCCESS statuses in color. Moreover, there is no coherent logging between scripts.

## Tasks

* [x] Add colors to every script
* [x] Use the new way of logging
```BASH
echo -e "${ERR}Build could not be commpleted!"
```
* [x] Use `printf` and formatting where possible

## Related

RUSTs _rustup_ has similar logging functionality.

**Comment by aendeavor** [comment]
Done. [02.01.20-19:55]
