### ISSUE TITLE
[DOC] Get the Markdown scripts right for new username

### ISSUE THREAD

**Issue by aendeavor** [aendeavor/i3buntu#32]
# New username

## Description

The new username _aendeavor_ makes old links obsolete. This must be corrected. Furthermore, the current **INSTALL.md and README.md are deprecated**!

## Tasks

* [x] Renew links in every file and in the wiki
* [x] Update `README.md`
* [x] Update `INSTALL.md`
* [x] Update `/doc/FEATURES.adoc`

## Meta

One might consider converting `.md` to `.adoc`.

## Related

**Comment by aendeavor** [comment]
Done. [03.01.20-14:33]
