### ISSUE TITLE
[TES] Beta testing of v0.9.2-beta.1

### ISSUE THREAD

**Issue by aendeavor** [aendeavor/i3buntu#34]
# Testing of v0.9.2-beta.1

## Description

The current release (v0.9.2.0-beta1) is not tested. Through the new `install.sh`, the desktop packaging and configuration, the server packaging and docker has to be tested.

## Tasks

* [x] test `get_docker.sh`

* [x] test `x_packaging.sh`
* [x] test `x_configuration.sh`
* [x] test `server_packaging.sh`
* [x] test `server_configuration.sh`
* [x] test `docker_up.sh`

## Related

#13

**Comment by aendeavor** [comment]
Done. [18.01.20-23:16]
