### ISSUE TITLE
[LOG] New logger functions

### ISSUE THREAD

**Issue by aendeavor** [aendeavor/i3buntu#35]
# New logger-functions

## Description

`./resources/sys/sh/.bash_aliases` provides new logger functions, and all script ought to use them.

## Tasks

* [x] Implement it in `sys/docker/docker_up.sh`
- [x] Implement it in `sys/docker/get_docker.sh`
- [x] Implement it in `sys/vscode/extensions.sh`
- [x] Implement it in `fonts/fonts.sh`

## Related

**Comment by aendeavor** [comment]
Done. [14.01.20-20:39]
