### ISSUE TITLE
Better Rofi

### ISSUE THREAD

**Issue by aendeavor** [aendeavor/i3buntu#44]
# Rofi configuration

## Description

The _Rofi_ application launcher can be configured via a `config`-file under `$HOME/.config/rofi/config`. This is to be used, as the configuration in `$HOME/.Xresources` is less maintainable.

## Tasks

* [x] Write a new `config` for _Rofi_ 
* [x] Delete old config from `.Xresources`
* [x] Sync the new config accordingly in `x_packaging.sh`

**Comment by aendeavor** [comment]
Done. [24.02.2020-16:12]
