### ISSUE TITLE
Testing under Ubuntu 20.04 Daily [Nightly]

### ISSUE THREAD

**Issue by aendeavor** [aendeavor/i3buntu#47]
# Ubuntu 20.04 Nightly build tests

## Description

As _Ubuntu 20.04 Focal Fossa_ daily builds are out, we can start testing with them.

## Tasks

* [x] Test server installation
* [x] Test desktop packaging
* [x] Test desktop configuration
* [x] Test VM Ware installation

**Comment by aendeavor** [comment]
Done. [07.03.2020-17:44]
