### ISSUE TITLE
Contracts and assertions

### ISSUE THREAD

**Issue by aendeavor** [aendeavor/i3buntu#55]
# Function contracts and assertions

## Description

The current bash functions work, but they do not fulfil contracts. They are not being asserted as well. Therefore, rustup-like function checking is to be introduced, where the caller of the function checks and asserts the callee.

# Tasks

* [x] Create caller functions
* [x] Implement the callers to call the normal functions
* [x]  Implement pre-checks (i.e. whether APT is there or not, etc.)

# Meta

See [Rustup’s init script](https://sh.rustup.rs).

**Comment by aendeavor** [comment]
Done. [18.03.2020-18:20]
