### ISSUE TITLE
Syncing Configuration Files

### ISSUE THREAD

**Issue by aendeavor** [aendeavor/i3buntu#60]
# Configuration Files

## Description

All needed configurations and images ought to be deployed in the correct place.

## Tasks

Deploy all files concerning

- [x] core configuration files (under `$HOME`, `/etc/X11/` and `/etc/lightdm/`)
- [x] WhiteSur theme (under `${HOME}/.theme/`) **including** unpacking the `.tar.xz`
- [x] LightDM's background image
- [x] default wallpapers

**Comment by aendeavor** [comment]
Syncing over `$HOME` is now **preferred**, as it integrates easier with all configuration files.

**Comment by aendeavor** [comment]
Done. [07.08.2020-18:29]
