### ISSUE TITLE
[CORE] Workspace Integration

### ISSUE THREAD

**Issue by aendeavor** [aendeavor/i3buntu#61]
# One Single Workspace

## Description

A few adjustments need to be made to handle the new structure with one workspace and multiple projects.

## Tasks

- [x] _Hermes_ is to be integrated
- [x] Makefile and build adjustment for _Kyrene_
- [x] `README.md` needs to be corrected

**Comment by aendeavor** [comment]
Done. [26.07.2020-13:17]
