### ISSUE TITLE
[BETA][CORE] Server Version

### ISSUE THREAD

**Issue by aendeavor** [aendeavor/i3buntu#66]
# Server Version

## Description

***APOLLO*** should be able to install a server version of itself.

## Tasks

- [ ] outsource the most important function from application (_Kyrene_) to library (_Athena_)
- [ ] create a co-routine to `main()` where the server version is started
- [ ] create lightweight stages similar to the desktop version reusing the data structures which are already present
